"""HTML reporter — generates a self-contained owner-audience HTML report."""

from __future__ import annotations

import html
from pathlib import Path

from ..chair import owner_summary
from ..schemas import ChairVerdict, ReviewerOutput, ReviewPack


_TRUST_COLORS = {
    "trusted": "#22c55e",
    "caution": "#eab308",
    "untrusted": "#ef4444",
}

_TRUST_ICONS = {
    "trusted": "&#x2705;",
    "caution": "&#x26A0;",
    "untrusted": "&#x274C;",
}


def _render_html(
    verdict: ChairVerdict,
    review_pack: ReviewPack | None = None,
    reviewer_outputs: list[ReviewerOutput] | None = None,
) -> str:
    """Render a self-contained HTML report for the owner audience."""
    summary = owner_summary(verdict, reviewer_outputs)
    trust = summary["trust_signal"]
    color = _TRUST_COLORS.get(trust, "#6b7280")
    icon = _TRUST_ICONS.get(trust, "")
    label = html.escape(summary["label"])
    headline = html.escape(summary["headline"])

    meta_lines = []
    if review_pack:
        meta_lines.append(f"Files changed: {len(review_pack.changed_files)}")
        meta_lines.append(f"Lines changed: {review_pack.total_lines_changed}")
        meta_lines.append(f"Languages: {', '.join(review_pack.languages_detected) or 'unknown'}")
    meta_html = "".join(f"<li>{html.escape(m)}</li>" for m in meta_lines)

    risks_html = ""
    if summary["top_risks"]:
        items = "".join(f"<li>{html.escape(r)}</li>" for r in summary["top_risks"])
        risks_html = f"<h2>Top Risks</h2><ol>{items}</ol>"

    health_html = ""
    if summary["reviewer_health"]:
        rows = ""
        for rh in summary["reviewer_health"]:
            status_icon = "&#x2705;" if rh["status"] == "ok" else "&#x26A0;"
            rows += f"<tr><td>{html.escape(rh['id'])}</td><td>{status_icon} {html.escape(rh['status'])}</td></tr>"
        health_html = (
            "<h2>Reviewer Panel</h2>"
            "<table><thead><tr><th>Reviewer</th><th>Status</th></tr></thead>"
            f"<tbody>{rows}</tbody></table>"
        )

    degraded_html = ""
    if verdict.degraded:
        reasons = "".join(f"<li>{html.escape(r)}</li>" for r in verdict.degraded_reasons)
        degraded_html = (
            '<div class="degraded">'
            "<strong>Integrity Issues Detected</strong>"
            f"<ul>{reasons}</ul></div>"
        )

    rationale_html = ""
    if verdict.rationale:
        rationale_html = f"<h2>Chair Rationale</h2><p>{html.escape(verdict.rationale)}</p>"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Code Review Council — {label}</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 720px; margin: 2rem auto; padding: 0 1rem; color: #1f2937; }}
  .verdict {{ background: {color}15; border-left: 4px solid {color};
              padding: 1.2rem; margin-bottom: 1.5rem; border-radius: 4px; }}
  .verdict h1 {{ margin: 0 0 0.4rem 0; font-size: 1.4rem; color: {color}; }}
  .verdict p {{ margin: 0; }}
  .meta {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 1.5rem; }}
  .meta ul {{ padding-left: 1.2rem; }}
  .degraded {{ background: #fef3c7; border-left: 4px solid #f59e0b;
               padding: 0.8rem; margin-bottom: 1.5rem; border-radius: 4px; }}
  table {{ border-collapse: collapse; width: 100%; margin-bottom: 1.5rem; }}
  th, td {{ text-align: left; padding: 0.5rem 0.8rem; border-bottom: 1px solid #e5e7eb; }}
  th {{ background: #f9fafb; font-weight: 600; }}
  h2 {{ font-size: 1.1rem; margin-top: 1.5rem; }}
  .confidence {{ font-size: 0.85rem; color: #6b7280; }}
</style>
</head>
<body>
<div class="verdict">
  <h1>{icon} {label}</h1>
  <p>{headline}</p>
  <p class="confidence">Confidence: {verdict.confidence:.0%}</p>
</div>
{degraded_html}
<div class="meta"><ul>{meta_html}</ul></div>
{risks_html}
{health_html}
{rationale_html}
<hr>
<p style="font-size:0.8rem;color:#9ca3af;">Generated by Code Review Council</p>
</body>
</html>"""


def write_html_report(
    verdict: ChairVerdict,
    output_path: str | Path,
    review_pack: ReviewPack | None = None,
    reviewer_outputs: list[ReviewerOutput] | None = None,
) -> None:
    """Write an owner-audience HTML report to disk."""
    content = _render_html(verdict, review_pack, reviewer_outputs)
    Path(output_path).write_text(content, encoding="utf-8")
