"""Diff Preprocessor — filter, prioritize, and budget-manage diffs.

Prevents cost blowup from lockfiles, generated code, vendored deps, etc.
Ensures token budget is spent on highest-risk code.

NOTE: Files exceeding max_file_tokens are currently truncated, not chunked
at logical boundaries. A future version may split at function/class boundaries.
"""

from __future__ import annotations

import fnmatch
import re
from pathlib import Path

import tiktoken

from .config import PreprocessorConfig, PreprocessorPriorities
from .schemas import DiffContext, DiffFile, DiffHunk

# Default ignore patterns (applied when no .councilignore exists)
DEFAULT_IGNORE_PATTERNS = [
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Pipfile.lock",
    "poetry.lock", "*.min.js", "*.min.css", "*.map",
    "*.generated.*", "vendor/", "dist/", "build/", "node_modules/",
    "__pycache__/", "*.egg-info/",
]

GENERATED_MARKERS = [
    "// @generated", "# @generated", "/* @generated",
    "# auto-generated", "// auto-generated", "# DO NOT EDIT",
    "// Code generated by", "# This file is generated",
]

# Security-sensitive path patterns (high priority)
SECURITY_PATTERNS = re.compile(
    r"(auth|login|password|crypto|secret|middleware|permission|token|session|oauth)",
    re.IGNORECASE,
)


def _load_ignore_patterns(repo_root: Path, ignore_file: str) -> list[str]:
    """Load ignore patterns from .councilignore or use defaults."""
    ignore_path = repo_root / ignore_file
    if ignore_path.exists():
        lines = ignore_path.read_text().splitlines()
        return [l.strip() for l in lines if l.strip() and not l.startswith("#")]
    return DEFAULT_IGNORE_PATTERNS


def _should_ignore(file_path: str, patterns: list[str]) -> bool:
    """Check if a file matches any ignore pattern (simple glob-like matching)."""
    path = Path(file_path)
    for pattern in patterns:
        if pattern.endswith("/"):
            # Directory pattern
            if pattern.rstrip("/") in file_path.split("/"):
                return True
        elif "*" in pattern:
            # Simple wildcard
            if fnmatch.fnmatch(path.name, pattern):
                return True
        else:
            # Exact filename match
            if path.name == pattern:
                return True
    return False


def _is_generated(diff_file: DiffFile) -> bool:
    """Detect auto-generated files by header markers."""
    if diff_file.source_content:
        first_lines = diff_file.source_content[:500]
        return any(marker in first_lines for marker in GENERATED_MARKERS)
    # Also check hunk content
    for hunk in diff_file.hunks:
        first_lines = hunk.content[:300]
        if any(marker in first_lines for marker in GENERATED_MARKERS):
            return True
    return False


def _truncate_to_tokens(text: str, max_tokens: int) -> str:
    """Truncate text to approximately max_tokens."""
    try:
        enc = tiktoken.get_encoding("cl100k_base")
        tokens = enc.encode(text)
        if len(tokens) <= max_tokens:
            return text
        truncated = enc.decode(tokens[:max_tokens])
        return truncated + "\n\n... [truncated by council preprocessor]\n"
    except Exception:
        # Fallback: ~4 chars per token
        char_limit = max_tokens * 4
        if len(text) <= char_limit:
            return text
        return text[:char_limit] + "\n\n... [truncated by council preprocessor]\n"


def _estimate_tokens(text: str) -> int:
    """Estimate token count for a string."""
    try:
        enc = tiktoken.get_encoding("cl100k_base")
        return len(enc.encode(text))
    except Exception:
        # Fallback: ~4 chars per token
        return len(text) // 4


def _file_priority(diff_file: DiffFile, priorities: PreprocessorPriorities | None = None) -> int:
    """Assign priority score to a file (higher = review first)."""
    if priorities is None:
        priorities = PreprocessorPriorities()

    path = diff_file.path.lower()

    if SECURITY_PATTERNS.search(path):
        return priorities.security

    if "test" in path or "spec" in path or "fixture" in path:
        return priorities.tests

    if diff_file.language in ("markdown", "toml", "yaml", "json"):
        return priorities.docs

    ext = Path(path).suffix
    if ext in (".md", ".txt", ".rst"):
        return priorities.docs

    if ext in (".toml", ".yaml", ".yml", ".json", ".cfg", ".ini"):
        return priorities.config

    return priorities.business  # default for source code


def process(
    diff_context: DiffContext,
    config: PreprocessorConfig,
    repo_root: Path | None = None,
) -> tuple[DiffContext, list[str], list[str]]:
    """Filter, prioritize, and budget-manage a diff.

    Returns:
        (processed_diff, skipped_files, truncated_files)
    """
    if repo_root is None:
        repo_root = Path.cwd()

    ignore_patterns = _load_ignore_patterns(repo_root, config.ignore_file)
    skipped_files: list[str] = []
    truncated_files: list[str] = []

    # Step 1: Filter out ignored and generated files
    kept_files: list[DiffFile] = []
    for f in diff_context.files:
        if _should_ignore(f.path, ignore_patterns):
            skipped_files.append(f.path)
            continue
        if config.detect_generated and _is_generated(f):
            skipped_files.append(f.path)
            continue
        kept_files.append(f)

    # Step 2: Sort by priority (highest first)
    kept_files.sort(key=lambda f: _file_priority(f, config.priorities), reverse=True)

    # Step 3: Token budget enforcement
    total_tokens = 0
    budget_files: list[DiffFile] = []

    for f in kept_files:
        file_text = "\n".join(h.content for h in f.hunks)
        file_tokens = _estimate_tokens(file_text)

        if file_tokens > config.max_file_tokens:
            # Actually truncate the content to fit per-file budget
            truncated_files.append(f.path)
            truncated_content = _truncate_to_tokens(file_text, config.max_file_tokens)
            f = DiffFile(
                path=f.path,
                language=f.language,
                change_type=f.change_type,
                additions=f.additions,
                deletions=f.deletions,
                hunks=[DiffHunk(
                    source_start=f.hunks[0].source_start if f.hunks else 0,
                    source_length=0,
                    target_start=f.hunks[0].target_start if f.hunks else 1,
                    target_length=0,
                    content=truncated_content,
                )],
                source_content=f.source_content,
            )
            file_tokens = config.max_file_tokens

        if total_tokens + file_tokens > config.max_review_tokens:
            # Budget exhausted — skip remaining lower-priority files
            skipped_files.append(f.path)
            continue

        total_tokens += file_tokens
        budget_files.append(f)

    # Build filtered DiffContext
    processed = DiffContext(
        files=budget_files,
        changed_files=[f.path for f in budget_files],
        added_files=[f.path for f in budget_files if f.change_type == "added"],
        deleted_files=[f.path for f in budget_files if f.change_type == "deleted"],
        branch=diff_context.branch,
        commit_range=diff_context.commit_range,
        total_additions=sum(f.additions for f in budget_files),
        total_deletions=sum(f.deletions for f in budget_files),
    )

    return processed, skipped_files, truncated_files
